"use client";

import Link from "next/link";
import { Send, ShieldCheck, Sparkles } from "lucide-react";
import { LanguageSwitcher, useTranslation } from "@/components/locale-provider";

export function SiteFooter() {
  const { t } = useTranslation();
  const links = [[t("common", "about"), "/#about"], [t("common", "privacyPolicy"), "/privacy"], [t("common", "terms"), "/terms"], [t("common", "communityGuidelines"), "/community-guidelines"], [t("common", "safety"), "/safety"], [t("common", "reportConcern"), "/safety"], [t("common", "becomeCompanion"), "/become-companion"]];
  return <footer className="relative overflow-hidden border-t border-white/10 bg-[#0d0918] px-5 pb-8 pt-16 text-white lg:px-8"><div className="absolute -left-32 top-0 h-72 w-72 rounded-full bg-fuchsia-500/15 blur-3xl" /><div className="absolute -right-24 bottom-0 h-72 w-72 rounded-full bg-cyan-400/12 blur-3xl" /><div className="relative mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr_1.2fr]"><section><Link href="/" className="inline-flex items-center gap-3"><span className="brand-glow grid h-11 w-11 place-items-center rounded-2xl text-base font-semibold">G</span><span className="brand-wordmark font-serif text-2xl">Gigolo India</span></Link><p className="mt-6 max-w-sm text-sm leading-7 text-violet-100/65">{t("common", "footerDescription")}</p><a href="https://t.me" target="_blank" rel="noreferrer" aria-label="Gigolo India on Telegram" className="mt-6 grid h-9 w-9 place-items-center rounded-full border border-white/15 bg-white/[.035] text-violet-100 transition hover:-translate-y-1 hover:border-cyan-300 hover:text-cyan-100"><Send size={16} /></a></section><section><p className="text-[10px] font-bold uppercase tracking-[.18em] text-cyan-100">{t("common", "explore")}</p><nav className="mt-5 grid gap-3 text-sm text-violet-100/70">{links.map(([label, href]) => <Link key={label} className="transition hover:text-cyan-100" href={href}>{label}</Link>)}<a className="transition hover:text-cyan-100" href="https://t.me" target="_blank" rel="noreferrer">{t("common", "contact")}</a></nav></section><section><ShieldCheck size={20} className="text-cyan-100" /><h2 className="mt-4 font-serif text-3xl">{t("common", "privacyPurpose")}</h2><p className="mt-4 max-w-md text-sm leading-7 text-violet-100/65">{t("common", "footerSafetyText")}</p><p className="mt-5 flex items-center gap-2 text-xs font-semibold text-cyan-100"><Sparkles size={13} /> {t("common", "consentFirst")}</p></section></div><div className="mt-14 flex flex-col gap-4 border-t border-white/10 pt-6 text-xs text-violet-100/45 sm:flex-row sm:items-center sm:justify-between"><span>{t("common", "copyright")}</span><LanguageSwitcher /><span>{t("common", "adultsOnly")}</span></div></div></footer>;
}
