"use client";

import { LocalizedLink as Link } from "@/components/localization-provider";
import { ShieldCheck, Sparkles } from "lucide-react";
import { LanguageSwitcher, useTranslation } from "@/components/localization-provider";
import { ROUTES } from "@/lib/routes";

export function SiteFooter() {
  const { t } = useTranslation();
  const links = [[t("common", "about"), `${ROUTES.home}#about`], [t("common", "privacyPolicy"), ROUTES.privacy], [t("common", "terms"), ROUTES.terms], [t("common", "communityGuidelines"), ROUTES.communityGuidelines], [t("common", "safety"), ROUTES.safety], [t("common", "reportConcern"), ROUTES.safety], [t("common", "becomeCompanion"), ROUTES.becomeCompanion]];
  return <footer className="relative overflow-hidden border-t border-white/10 bg-[#0d0918] px-5 pb-8 pt-16 text-white lg:px-8"><div className="absolute -left-32 top-0 h-72 w-72 rounded-full bg-fuchsia-500/15 blur-3xl" /><div className="absolute -right-24 bottom-0 h-72 w-72 rounded-full bg-cyan-400/12 blur-3xl" /><div className="relative mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr_1.2fr]"><section><Link href="/" className="inline-flex items-center gap-3"><span className="brand-glow grid h-11 w-11 place-items-center rounded-2xl text-base font-semibold">G</span><span className="brand-wordmark font-serif text-2xl">Gigolo India</span></Link><p className="mt-6 max-w-sm text-sm leading-7 text-violet-100/65">{t("common", "footerDescription")}</p></section><section><p className="text-[10px] font-bold uppercase tracking-[.18em] text-cyan-100">{t("common", "explore")}</p><nav className="mt-5 grid gap-3 text-sm text-violet-100/70">{links.map(([label, href]) => <Link key={label} className="transition hover:text-cyan-100" href={href}>{label}</Link>)}<Link className="transition hover:text-cyan-100" href={`${ROUTES.safety}#report`}>{t("common", "contact")}</Link></nav></section><section><ShieldCheck size={20} className="text-cyan-100" /><h2 className="mt-4 font-serif text-3xl">{t("common", "privacyPurpose")}</h2><p className="mt-4 max-w-md text-sm leading-7 text-violet-100/65">{t("common", "footerSafetyText")}</p><p className="mt-5 flex items-center gap-2 text-xs font-semibold text-cyan-100"><Sparkles size={13} /> {t("common", "consentFirst")}</p></section></div><div className="mt-14 flex flex-col gap-4 border-t border-white/10 pt-6 text-xs text-violet-100/45 sm:flex-row sm:items-center sm:justify-between"><span>{t("common", "copyright")}</span><LanguageSwitcher /><span>{t("common", "adultsOnly")}</span></div></div></footer>;
}
