"use client";

import Link from "next/link";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, BadgeCheck, CalendarDays, Check, ChevronRight, Crown, LockKeyhole, MapPin, MessageCircle, ShieldCheck, Sparkles, Star, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import { LanguageSwitcher, useLocale } from "@/components/locale-provider";
import { MemberMenu, type SessionMember } from "@/components/member-menu";
import { SiteFooter } from "@/components/site-footer";

type Companion = { name: string; age: number; city: string; vibe: string; tags: string[]; shade: string };

const companions: Companion[] = [
  { name: "Aarav", age: 27, city: "Mumbai", vibe: "Charming · Good listener", tags: ["Dinner", "Easygoing"], shade: "from-fuchsia-500/45 via-violet-950 to-cyan-400/30" },
  { name: "Kabir", age: 29, city: "Delhi", vibe: "Gentleman · Traveller", tags: ["Events", "Travel"], shade: "from-cyan-400/30 via-[#151022] to-fuchsia-500/35" },
  { name: "Vihaan", age: 26, city: "Bengaluru", vibe: "Athletic · Social", tags: ["Night out", "Fitness"], shade: "from-amber-200/20 via-fuchsia-700/40 to-cyan-300/25" },
  { name: "Arjun", age: 30, city: "Hyderabad", vibe: "Quiet confidence", tags: ["Culture", "Conversation"], shade: "from-violet-500/40 via-[#161024] to-cyan-300/30" },
  { name: "Rey", age: 28, city: "Goa", vibe: "Traveller · Easygoing", tags: ["Getaway", "Sunset"], shade: "from-cyan-300/35 via-violet-950 to-amber-200/25" },
  { name: "Ishaan", age: 27, city: "Pune", vibe: "Wingman · Gentleman", tags: ["Party", "Dining"], shade: "from-fuchsia-400/35 via-[#151022] to-cyan-300/35" },
];

const vibes = ["The Gentleman", "The Athlete", "The Party Starter", "The Silent Type", "The Traveller", "The Wingman"];
const faq = [
  ["How do I book?", "Message a companion, agree on the plan and boundaries, and confirm through the platform."],
  ["Is my data private?", "Yes. Aliases, encrypted chats, and neutral billing are standard."],
  ["What does PRISM add?", "Priority access, unblurred galleries, exclusive companions, and concierge booking."],
  ["Something felt wrong. What do I do?", "Use the report button. Our team responds 24/7."],
];

function AbstractProfile({ companion, locked = false }: { companion: Companion; locked?: boolean }) {
  return <div className={`relative aspect-[1.06] overflow-hidden bg-gradient-to-br ${companion.shade}`}>
    <div className={`absolute inset-x-[27%] top-[12%] h-[67%] rounded-[45%] border border-white/25 bg-white/10 ${locked ? "blur-md" : "blur-[1px]"}`} />
    <div className={`absolute -right-8 top-5 h-32 w-32 rounded-full border-[15px] border-cyan-100/15 ${locked ? "blur-md" : ""}`} />
    <div className="absolute inset-x-0 bottom-0 h-1/2 bg-gradient-to-t from-[#100a1c]/85 to-transparent" />
    {locked ? <span className="absolute inset-0 grid place-items-center bg-[#0d0918]/20"><span className="grid h-11 w-11 place-items-center rounded-full border border-white/30 bg-black/45 text-white backdrop-blur"><LockKeyhole size={17} /></span></span> : <span className="absolute bottom-3 left-3 inline-flex items-center gap-1.5 rounded-full bg-emerald-300/15 px-2.5 py-1 text-[10px] font-semibold text-emerald-100 backdrop-blur"><span className="h-1.5 w-1.5 rounded-full bg-emerald-300 shadow-[0_0_10px_#86efac]" /> Available now</span>}
  </div>;
}

function CompanionCard({ companion, recommended = false }: { companion: Companion; recommended?: boolean }) {
  return <article className="min-w-[16.5rem] overflow-hidden rounded-[1.5rem] border border-white/12 bg-[#151022] shadow-xl shadow-black/10 sm:min-w-0">
    <AbstractProfile companion={companion} />
    <div className="p-5">
      <div className="flex items-start justify-between gap-3"><div><h3 className="font-serif text-3xl">{companion.name}, {companion.age}</h3><p className="mt-1 flex items-center gap-1 text-xs text-violet-100/60"><MapPin size={13} /> {companion.city}</p></div><BadgeCheck size={18} className="mt-1 shrink-0 text-cyan-100" aria-label="Verified profile" /></div>
      <p className="mt-3 text-sm text-violet-100/70">{companion.vibe}</p>
      <div className="mt-3 flex flex-wrap gap-1.5">{companion.tags.map((tag) => <span key={tag} className="rounded-full border border-white/12 bg-white/[.035] px-2 py-1 text-[10px] text-violet-100/65">{tag}</span>)}</div>
      <Link href="/browse" className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-full border border-cyan-200/30 bg-cyan-200/10 px-4 py-2.5 text-sm font-bold text-cyan-100 transition hover:bg-cyan-200 hover:text-mauve-950">{recommended ? "Message" : "View Profile"} <ArrowRight size={14} /></Link>
    </div>
  </article>;
}

export function StandardMemberHome({ member }: { member: SessionMember }) {
  const reduceMotion = useReducedMotion();
  const { t } = useLocale();
  const [unreadCount, setUnreadCount] = useState(0);
  const firstName = member.name.trim().split(/\s+/)[0] || member.name;
  const city = member.city;
  const availableCount = 24;
  const bookingCount = 0;
  const cityCompanions = companions.filter((companion) => companion.city === city);
  const availableCompanions = cityCompanions.length ? cityCompanions : companions.slice(0, 4);

  useEffect(() => {
    let active = true;
    fetch("/api/messages", { cache: "no-store" })
      .then((response) => response.ok ? response.json() as Promise<{ unreadCount?: unknown }> : null)
      .then((data) => {
        if (active && typeof data?.unreadCount === "number") setUnreadCount(Math.max(0, data.unreadCount));
      })
      .catch(() => undefined);
    return () => { active = false; };
  }, []);

  return <main className="min-h-screen overflow-hidden bg-[#0d0918] text-white">
    <div className="pointer-events-none fixed inset-0 -z-0 overflow-hidden"><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(rgba(208,201,213,.055)_1px,transparent_1px),linear-gradient(90deg,rgba(208,201,213,.055)_1px,transparent_1px)] [background-size:42px_42px]" /><motion.div animate={reduceMotion ? undefined : { x: [0, 70, 0], y: [0, -30, 0] }} transition={{ duration: 15, repeat: Infinity, ease: "easeInOut" }} className="absolute -left-32 top-20 h-96 w-96 rounded-full bg-fuchsia-500/15 blur-[150px]" /><motion.div animate={reduceMotion ? undefined : { x: [0, -60, 0], y: [0, 45, 0] }} transition={{ duration: 18, repeat: Infinity, ease: "easeInOut" }} className="absolute -right-32 bottom-0 h-96 w-96 rounded-full bg-cyan-400/15 blur-[150px]" /></div>

    <nav className="relative z-20 mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-5 lg:px-8">
      <Link href="/" className="flex shrink-0 items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl border border-white/20 bg-white/[.06] text-cyan-100"><Sparkles size={18} /></span><span><span className="brand-wordmark block text-[10px] font-bold uppercase tracking-[.24em]">GIGOLO INDIA</span><span className="mt-0.5 block font-serif text-lg tracking-[.1em]">MEMBER</span></span></Link>
      <div className="hidden items-center gap-5 text-sm text-violet-100/70 lg:flex"><Link href="/browse" className="transition hover:text-cyan-100">Browse</Link><Link href="/messages" className="inline-flex items-center gap-1.5 transition hover:text-cyan-100">Messages <span className="inline-flex h-5 min-w-5 items-center justify-center rounded-full bg-cyan-200 px-1 text-[10px] font-bold leading-none tabular-nums text-mauve-950">{unreadCount}</span></Link><a href="#bookings" className="transition hover:text-cyan-100">Bookings</a><Link href="/membership" className="transition hover:text-cyan-100">Membership</Link></div>
      <div className="flex items-center gap-2"><LanguageSwitcher /><Link href="/membership" className="hidden items-center gap-2 rounded-full border border-amber-100/30 bg-amber-100/10 px-4 py-2 text-sm font-bold text-amber-100 transition hover:bg-amber-100 hover:text-mauve-950 sm:inline-flex"><Crown size={15} /> Upgrade to PRISM</Link><MemberMenu member={member} /></div>
    </nav>

    <section className="relative z-10 mx-auto max-w-7xl px-5 pb-12 pt-10 lg:px-8 lg:pb-16 lg:pt-16"><div className="rounded-[2rem] border border-white/12 bg-[radial-gradient(circle_at_14%_14%,rgba(217,70,239,.24),transparent_33%),radial-gradient(circle_at_90%_78%,rgba(34,211,238,.18),transparent_36%),#151022] p-7 shadow-2xl shadow-black/20 sm:p-10"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-cyan-100">MEMBER · {city}</p><h1 className="mt-4 font-serif text-5xl tracking-[-.065em] sm:text-6xl">{t("standard", "welcome", { firstName })}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-violet-100/75">{t("standard", "availability", { city, count: availableCount })}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={`/browse?city=${encodeURIComponent(city)}`} className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-mauve-950 transition hover:bg-cyan-100">{t("standard", "browseCity", { city })} <ArrowRight size={16} /></Link><a href="#bookings" className="inline-flex items-center gap-2 rounded-full border border-white/18 bg-white/[.04] px-5 py-3 text-sm font-bold text-white transition hover:border-cyan-200 hover:text-cyan-100"><CalendarDays size={16} /> View My Bookings</a></div><Link href="/profile" className="mt-6 inline-flex text-sm font-semibold text-cyan-100 transition hover:text-white">Not in {city}? Change city <ChevronRight size={15} /></Link></div></section>

    <section className="relative z-10 mx-auto max-w-7xl px-5 pb-12 lg:px-8"><div className="grid grid-cols-2 gap-3 sm:gap-4 xl:grid-cols-4">{[[UsersRound, "Browse Companions", "Find your vibe.", "/browse"], [MessageCircle, "Messages", `${unreadCount} new messages.`, "/messages"], [CalendarDays, "My Bookings", `${bookingCount} upcoming.`, "#bookings"], [ShieldCheck, "Safety Centre", "Guidelines and one-tap support.", "/safety"]].map(([Icon, title, copy, href]) => { const Glyph = Icon as typeof UsersRound; return <Link key={String(title)} href={String(href)} className="group min-w-0 rounded-[1.25rem] border border-white/12 bg-white/[.035] p-4 transition active:scale-[.98] hover:-translate-y-1 hover:border-cyan-200/40 hover:bg-white/[.06] sm:rounded-[1.4rem] sm:p-5"><Glyph size={18} className="text-cyan-100 sm:h-5 sm:w-5" /><h2 className="mt-3 text-sm font-semibold leading-5 sm:mt-5 sm:text-lg">{String(title)}</h2><p className="mt-1.5 text-xs leading-5 text-violet-100/65 sm:mt-2 sm:text-sm">{String(copy)}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-cyan-100 sm:mt-5 sm:text-sm">Open <ArrowRight size={14} /></span></Link>; })}</div></section>

    <section className="relative z-10 mx-auto max-w-7xl px-5 py-12 lg:px-8 lg:py-16"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-cyan-100">IN {city.toUpperCase()}</p><h2 className="mt-3 font-serif text-4xl tracking-[-.055em]">Available tonight.</h2><p className="mt-3 text-sm text-violet-100/65">Verified companions ready to meet in {city}.</p></div><Link href={`/browse?city=${encodeURIComponent(city)}`} className="inline-flex items-center gap-1 text-sm font-semibold text-cyan-100 transition hover:text-white">See all companions <ArrowRight size={15} /></Link></div><div className="mt-8 flex snap-x gap-5 overflow-x-auto pb-3 [scrollbar-width:thin] md:grid md:grid-cols-2 md:overflow-visible xl:grid-cols-4">{availableCompanions.map((companion) => <div key={companion.name} className="snap-start md:min-w-0"><CompanionCard companion={companion} /></div>)}</div></section>

    <section className="relative z-10 border-y border-white/10 bg-white/[.025] px-5 py-12 lg:px-8 lg:py-16"><div className="mx-auto max-w-7xl"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-cyan-100">PICK YOUR VIBE</p><h2 className="mt-3 font-serif text-4xl tracking-[-.055em]">What are you in the mood for?</h2><div className="mt-8 flex flex-wrap gap-3">{vibes.map((vibe) => <Link key={vibe} href={`/browse?vibe=${encodeURIComponent(vibe)}`} className="rounded-full border border-white/15 bg-[#151022] px-4 py-2.5 text-sm font-semibold text-violet-100 transition hover:border-cyan-200 hover:bg-cyan-200/10 hover:text-cyan-100">{vibe}</Link>)}</div></div></section>

    <section className="relative z-10 mx-auto max-w-7xl px-5 py-12 lg:px-8 lg:py-16"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-cyan-100">RECOMMENDED FOR YOU</p><h2 className="mt-3 font-serif text-4xl tracking-[-.055em]">Picked for you.</h2><p className="mt-3 text-sm text-violet-100/65">Based on your city and the vibes you&apos;ve explored.</p></div><p className="text-sm text-violet-100/55">Start browsing and we&apos;ll learn your taste.</p></div><div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{companions.slice(0, 4).map((companion) => <CompanionCard key={companion.name} companion={companion} recommended />)}</div></section>

    <section className="relative z-10 mx-auto max-w-7xl px-5 py-12 lg:px-8 lg:py-16"><div className="grid gap-5 lg:grid-cols-2"><article id="chats" className="rounded-[1.75rem] border border-white/12 bg-[#151022]/85 p-6 shadow-xl shadow-black/10"><MessageCircle size={21} className="text-cyan-100" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.18em] text-violet-100/45">YOUR CHATS</p><h2 className="mt-2 font-serif text-3xl">Your conversations.</h2><p className="mt-4 max-w-md text-sm leading-6 text-violet-100/65">No messages yet. Say hello to someone interesting.</p><Link href="/messages" className="mt-7 inline-flex items-center gap-2 rounded-full border border-cyan-200/30 bg-cyan-200/10 px-4 py-2.5 text-sm font-bold text-cyan-100 transition hover:bg-cyan-200 hover:text-mauve-950">Open Messages <ArrowRight size={15} /></Link></article><article id="bookings" className="rounded-[1.75rem] border border-white/12 bg-[#151022]/85 p-6 shadow-xl shadow-black/10"><CalendarDays size={21} className="text-cyan-100" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.18em] text-violet-100/45">YOUR BOOKINGS</p><h2 className="mt-2 font-serif text-3xl">Your plans.</h2><p className="mt-4 max-w-md text-sm leading-6 text-violet-100/65">No plans yet. Tonight could change that.</p><Link href="/browse" className="mt-7 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2.5 text-sm font-bold text-mauve-950 transition hover:bg-cyan-100">Browse Companions <ArrowRight size={15} /></Link></article></div></section>

    <section className="relative z-10 border-y border-amber-100/15 bg-[#171024] px-5 py-14 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl rounded-[2rem] border border-amber-100/25 bg-[radial-gradient(circle_at_12%_15%,rgba(251,191,36,.14),transparent_34%),radial-gradient(circle_at_90%_75%,rgba(34,211,238,.12),transparent_35%),#1a1026] p-7 sm:p-10"><div className="max-w-3xl"><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-amber-100"><Crown size={14} /> PRISM PREMIUM</p><h2 className="mt-4 font-serif text-4xl tracking-[-.06em] sm:text-5xl">You&apos;re in. Now go inside the inner circle.</h2><p className="mt-5 text-base leading-7 text-violet-100/75">PRISM members get priority access, unblurred galleries, exclusive companions, and a personal concierge who arranges everything for you.</p></div><div className="mt-9 overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-[38rem] w-full text-left text-sm"><thead className="border-b border-white/10 bg-white/[.04] text-violet-100/70"><tr><th className="px-5 py-4 font-semibold">Feature</th><th className="px-5 py-4 font-semibold">Standard</th><th className="px-5 py-4 font-semibold text-amber-100">PRISM</th></tr></thead><tbody>{[["Browse verified profiles", true], ["Message companions", true], ["Unblurred photo galleries", false], ["Priority booking", false], ["PRISM-only companions", false], ["Concierge booking", false], ["Travel and event booking", false], ["Private mode", false], ["Priority 24/7 support", false]].map(([feature, standard]) => <tr key={String(feature)} className="border-b border-white/10 last:border-0"><td className="px-5 py-3.5 text-violet-100/75">{String(feature)}</td><td className="px-5 py-3.5">{standard ? <Check size={16} className="text-cyan-100" /> : <span className="text-violet-100/35">—</span>}</td><td className="px-5 py-3.5"><Check size={16} className="text-amber-100" /></td></tr>)}</tbody></table></div><div className="mt-8 flex flex-wrap items-center gap-3"><Link href="/membership" className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-mauve-950 transition hover:bg-amber-100"><Crown size={16} /> Upgrade to PRISM</Link><Link href="/membership" className="inline-flex items-center gap-2 rounded-full border border-white/20 px-5 py-3 text-sm font-bold text-white transition hover:border-amber-100 hover:text-amber-100">Compare Plans <ArrowRight size={16} /></Link><span className="text-xs text-violet-100/55">Cancel anytime. Discreet billing.</span></div></div></section>

    <section className="relative z-10 mx-auto max-w-7xl px-5 py-12 lg:px-8 lg:py-16"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-amber-100">PRISM-ONLY</p><h2 className="mt-3 font-serif text-4xl tracking-[-.055em]">Behind the velvet rope.</h2><p className="mt-3 text-sm text-violet-100/65">Exclusive companions are visible to PRISM members only.</p></div><Link href="/membership" className="inline-flex items-center gap-2 self-start rounded-full border border-amber-100/35 bg-amber-100/10 px-4 py-2.5 text-sm font-bold text-amber-100 transition hover:bg-amber-100 hover:text-mauve-950">Unlock with PRISM <LockKeyhole size={15} /></Link></div><div className="mt-8 grid gap-5 sm:grid-cols-3">{companions.slice(3, 6).map((companion) => <article key={companion.name} className="overflow-hidden rounded-[1.5rem] border border-white/12 bg-[#151022]"><AbstractProfile companion={companion} locked /><div className="p-5"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-amber-100">PRISM ONLY</p><div className="mt-2 flex items-center justify-between"><h3 className="font-serif text-3xl blur-[5px]">{companion.name}</h3><LockKeyhole size={16} className="text-amber-100" /></div><p className="mt-3 text-sm text-violet-100/55">Exclusive profile</p></div></article>)}</div></section>

    <section className="relative z-10 border-y border-white/10 bg-white/[.025] px-5 py-12 lg:px-8 lg:py-16"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-cyan-100">SAFETY & PRIVACY</p><h2 className="mt-3 font-serif text-4xl tracking-[-.055em]">Your night. Your secret.</h2></div><Link href="/safety" className="inline-flex items-center gap-1 text-sm font-semibold text-cyan-100 transition hover:text-white">Read our safety guide <ArrowRight size={15} /></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[LockKeyhole, "Encrypted chats"], [ShieldCheck, "Neutral billing"], [UsersRound, "Alias name"], [Star, "One-tap report and block"]].map(([Icon, label]) => { const Glyph = Icon as typeof LockKeyhole; return <div key={String(label)} className="flex items-center gap-3 rounded-2xl border border-white/12 bg-[#151022] p-5"><Glyph size={18} className="text-cyan-100" /><span className="text-sm font-semibold">{String(label)}</span></div>; })}</div></div></section>

    <section className="relative z-10 mx-auto max-w-7xl px-5 py-12 lg:px-8 lg:py-16"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-cyan-100">HOW BOOKING WORKS</p><h2 className="mt-3 font-serif text-4xl tracking-[-.055em]">Clear from the first move.</h2><div className="mt-8 grid gap-4 md:grid-cols-4">{[["01", "Browse", "Pick a companion."], ["02", "Chat", "Agree on the plan and boundaries."], ["03", "Confirm", "Book through the platform."], ["04", "Meet", "Meet safely and rate the experience."]].map(([step, title, copy]) => <article key={step} className="rounded-2xl border border-white/12 bg-white/[.035] p-5"><span className="text-xs font-bold text-cyan-100">{step}</span><h3 className="mt-7 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-violet-100/65">{copy}</p></article>)}</div></section>

    <section className="relative z-10 mx-auto max-w-5xl px-5 py-12 lg:px-8 lg:py-16"><p className="text-center text-[10px] font-bold uppercase tracking-[.2em] text-cyan-100">HELP / FAQ</p><h2 className="mt-3 text-center font-serif text-4xl tracking-[-.055em]">Clear answers, before you begin.</h2><div className="mt-8 space-y-3">{faq.map(([question, answer]) => <details key={question} className="group rounded-2xl border border-white/12 bg-white/[.035] p-5"><summary className="cursor-pointer list-none text-base font-semibold marker:hidden">{question}<span className="float-right text-cyan-100 transition group-open:rotate-45">+</span></summary><p className="mt-3 pr-8 text-sm leading-6 text-violet-100/65">{answer}</p></details>)}</div></section>

    <section className="relative z-10 px-5 pb-16 pt-8 text-center lg:px-8 lg:pb-24"><div className="mx-auto max-w-4xl rounded-[2rem] border border-cyan-200/25 bg-[radial-gradient(circle_at_20%_10%,rgba(217,70,239,.2),transparent_35%),radial-gradient(circle_at_85%_85%,rgba(34,211,238,.16),transparent_32%),#151022] p-8 sm:p-12"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-amber-100">PRISM PREMIUM</p><h2 className="mt-4 font-serif text-5xl tracking-[-.06em]">Ready for more?</h2><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-violet-100/70">Step up to PRISM and let the night come to you.</p><Link href="/membership" className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-bold text-mauve-950 transition hover:bg-amber-100"><Crown size={16} /> Upgrade to PRISM</Link></div></section>
    <SiteFooter />
  </main>;
}
