"use client";

import Link from "next/link";
import { ArrowRight, Check, Crown } from "lucide-react";
import { useUpgradeModal } from "@/components/prism-upgrade-modal";

const standard = ["Browse profiles", "Blurred photos until verified", "Message companions", "Standard booking", "Standard support"];
const prism = ["Unblurred galleries", "Priority booking", "Early access to new companions", "Concierge booking", "Priority 24/7 support", "Private-mode invisibility", "PRISM-only companions", "Travel and event booking"];

export default function MembershipPage() {
  const { openUpgradeModal } = useUpgradeModal();
  return <main className="min-h-screen bg-[#0d0918] px-5 py-5 text-white lg:px-8">
    <nav className="mx-auto flex max-w-7xl items-center justify-between py-2"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl border border-white/20 bg-white/[.06] text-cyan-100"><Crown size={18} /></span><span className="brand-wordmark font-serif text-xl">Gigolo India</span></Link><Link href="/register" className="rounded-full bg-white px-4 py-2 text-sm font-bold text-mauve-950">Join Now</Link></nav>
    <section className="mx-auto max-w-6xl py-16 text-center lg:py-24"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-cyan-100">MEMBERSHIP</p><h1 className="mt-3 font-serif text-5xl tracking-[-.06em] sm:text-6xl">Go Standard. Or go <span className="text-amber-100">PRISM.</span></h1><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-violet-100/70">Choose the level of access that fits your plans. Every tier is discreet and adults-only.</p><div className="mt-12 grid gap-6 text-left md:grid-cols-2"><article className="rounded-[2rem] border border-white/12 bg-[#151022] p-7 sm:p-8"><h2 className="font-serif text-4xl">Standard</h2><p className="mt-3 text-sm text-violet-100/65">Free</p><ul className="mt-8 grid gap-3">{standard.map((item) => <li key={item} className="flex items-center gap-3 text-sm text-violet-100/80"><Check size={16} className="text-cyan-100" />{item}</li>)}</ul><Link href="/register" className="mt-9 inline-flex w-full items-center justify-center gap-2 rounded-full border border-white/20 px-5 py-3 text-sm font-bold transition hover:bg-white hover:text-mauve-950">Join Standard <ArrowRight size={16} /></Link></article><article className="rounded-[2rem] border border-amber-100/35 bg-[radial-gradient(circle_at_20%_10%,rgba(251,191,36,.14),transparent_32%),#20152a] p-7 sm:p-8"><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-amber-100"><Crown size={14} /> PREMIUM</p><h2 className="mt-2 font-serif text-4xl">PRISM</h2><ul className="mt-8 grid gap-3">{prism.map((item) => <li key={item} className="flex items-center gap-3 text-sm text-violet-100/80"><Check size={16} className="text-amber-100" />{item}</li>)}</ul><button type="button" onClick={() => openUpgradeModal("membership_page")} className="mt-9 inline-flex w-full items-center justify-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-mauve-950 transition hover:bg-amber-100">Upgrade to PRISM <ArrowRight size={16} /></button></article></div><p className="mt-7 text-xs text-violet-100/50">Cancel anytime. Discreet billing.</p></section>
  </main>;
}
